### ISSUE TITLE
[req] Find the true bitrate of all audio files

### ISSUE THREAD

**Issue by ghost** [mevdschee/fakeflac#1]
I'm trying to find a way to quickly display the true bitrate of mp3, flac and similar audio formats. Spek is the tool I use when I want to process a single song in a GUI, but nothing seems to exist for the command line.

Fakeflac seemed a good starting point, and I was able to make it work with other (e.g. mp3) file formats by replacing sndfile-convert with sox. I tried printing the cutoff and freq variables but my knowledge of this field is very limited, so I don't know how to make it show the actual bitrate in KBPS. Any help would be very appreciated!

**Comment by mevdschee** [comment]
Hi,

>my knowledge of this field is very limited, 

Mine as limited as well.

>so I don't know how to make it show the actual bitrate in KBPS

I think all we can do is frequency analysis to detect low pass filters. Frequency analysis gives you a percentage of the spectrum that is in use (which is the number that is reported). I don't think it is possible to deduce the bitrate in KBPS from that.

**Comment by dvorapa** [comment]
There are some frequencies, for which bitrate in kbps is known. I forked FakeFLAC and modified the output according to those (https://github.com/dvorapa/true-bitrate). Maybe there could be found some correlation, but I just quickly created it for myself some years ago, didn't have time to analyze it deeper that time.
