### ISSUE TITLE
use ffmpeg instead sndfile-convert for wav conversion

### ISSUE THREAD

**Issue by eadmaster** [mevdschee/fakeflac#5]
`ffmpeg` builds are easily available in more systems than `sndfile-convert` (i am expecially thinking to Windows).

The check should be like this:
````
CONVERT="`which ffmpeg ` -v quiet -i"
if [ $? -eq 1 ]; then
  echo "Cannot find 'ffmpeg' executable, is 'ffmpeg' installed?"
  exit -1
fi
````

**Comment by mevdschee** [comment]
agree.. something like that.. did you test it?

**Comment by eadmaster** [comment]
yes, i've just tested it and it works!

**Comment by mevdschee** [comment]
This is an issue not a PR.. if you update the README as well, then I'll be happy to merge it!
