### ISSUE TITLE
MQA counts as FLAC?

### ISSUE THREAD

**Issue by bydioeds** [mevdschee/fakeflac#8]
I'm really sorry to open an issue to ask this maybe stupid question, but this tools sees MQA as a true FLAC?

Again sorry.

**Comment by mevdschee** [comment]
Don't be sorry, your question is not stupid at all. I guess that MQA does not apply a (strong) low-pass filter and is thus not recognized as lossy or a "fake" flac.

**Comment by bydioeds** [comment]
> Don't be sorry, your question is not stupid at all. I guess that MQA does not apply a (strong) low-pass filter and is thus not recognized as lossy or a "fake" flac.

Thanks for your reply, i was going to ask or a tool to do that but i just found one https://github.com/redsudo/mqaid

PD: Thanks for your hard work!
